# To Calculate the distances between any two cities Binghamton, Hancock, Middletown, Sloatsburg and New York.
Distances measured are in miles and the City Binghamton is taken as the benchmark and all the distances entered in the array miles are measured from the benchmark.

In [1]:
import numpy as np

In [3]:
miles=np.array([0,43,120,153,190]ew York)
miles

array([  0,  43, 120, 153, 190])

Now we transform the row matrix into a column one:

In [4]:
miles.reshape(5,1)

array([[  0],
       [ 43],
       [120],
       [153],
       [190]])

In [5]:
miles-miles.reshape(5,1)

array([[   0,   43,  120,  153,  190],
       [ -43,    0,   77,  110,  147],
       [-120,  -77,    0,   33,   70],
       [-153, -110,  -33,    0,   37],
       [-190, -147,  -70,  -37,    0]])

And Hence we get distances from various different cities in an orderly fashion in the form of an array where the first column shows the distances of various cities from Binghamton, sencond one shows the distances of the cities from Hancock and so on.. in the order: 1)Binghamton.
           2)Hancock.
           3)Middletown.
           4)Sloatsburg.
           5)New York.

# Finding the Nearest Neighbours of 1000 random points in 3d space:

1000 Points in 3 dimensions:

In [42]:
X=np.random.random((1000,3))

In [43]:
X.shape

(1000, 3)

Broadcasting to find Pair-wise differences:

In [44]:
diff=(X.reshape(1000,1,3))-X

In [45]:
diff.shape

(1000, 1000, 3)

Aggregate to find Pair-wise distances:

In [46]:
D=(diff**2).sum(2)

In [47]:
D.shape

(1000, 1000)

Set Diagonal to Infinity to skip self neighbors:

In [48]:
i=np.arange(1000)
i

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [49]:
D[i,i]=np.inf

In [50]:
D

array([[        inf,  0.14466559,  0.52911553, ...,  0.30495274,
         0.48898217,  0.29106789],
       [ 0.14466559,         inf,  0.66048639, ...,  0.35537986,
         0.28923654,  0.16195858],
       [ 0.52911553,  0.66048639,         inf, ...,  0.16863721,
         0.22721432,  0.28228573],
       ..., 
       [ 0.30495274,  0.35537986,  0.16863721, ...,         inf,
         0.19699244,  0.076914  ],
       [ 0.48898217,  0.28923654,  0.22721432, ...,  0.19699244,
                inf,  0.0690107 ],
       [ 0.29106789,  0.16195858,  0.28228573, ...,  0.076914  ,
         0.0690107 ,         inf]])

Print the indices of the nearest neighbour:

In [54]:
i=np.argmin(D,1)

In [55]:
print(i[:10])

[610 566 365 906 247 923 844 490 278 897]


Double check with Scikit-Learn

In [40]:
from sklearn.neighbours import NearestNeighbors

ModuleNotFoundError: No module named 'sklearn.neighbours'

In [41]:
d,i= NearestNeighbors().Fit(X).Kneighbors(X,2)

NameError: name 'NearestNeighbors' is not defined